parameters:
    csbill_payment.menu.top.class: CSBill\PaymentBundle\Menu\PaymentsMenu
    csbill.payment.payum.paypal_express.action.capture_order.class: CSBill\PaymentBundle\Action\PaypalExpress\CaptureOrderAction
    csbill.payment.payum.paypal_express.action.payment_status.class: CSBill\PaymentBundle\Action\PaypalExpress\PaymentDetailsStatusAction
    csbill.payment.payum.offline.action.status_action.class: CSBill\PaymentBundle\Action\Offline\StatusAction
    csbill.payment.event.subscriber.class: CSBill\PaymentBundle\Listener\PaymentSubscriber
    csbill.payment.twig_extension.class: CSBill\PaymentBundle\Twig\PaymentExtension

services:
    csbill_payment.menu.top:
        class: %csbill_payment.menu.top.class%
        tags:
            - { name: cs_core.menu, menu: top_right, method: topRightMenu }
            - { name: cs_core.menu, menu: top, method: topMenu }

    csbill_payment.method.manager:
        class: CSBill\PaymentBundle\Manager\PaymentMethodManager
        arguments: [@payum]

    csbill.payment.payum.paypal_express.action.capture_order_action:
        class: %csbill.payment.payum.paypal_express.action.capture_order.class%
        arguments: [@payum.security.token_factory, %currency%]

    csbill.payment.payum.paypal_express.action.payment_status_action:
        class: %csbill.payment.payum.paypal_express.action.payment_status.class%
        arguments: [@payum.security.token_factory, %currency%]

    csbill.payment.payum.offline.action.status_action:
        class: %csbill.payment.payum.offline.action.status_action.class%

    csbill.payment.payum.paypal_express_checkout_api:
        class: Payum\Paypal\ExpressCheckout\Nvp\Api
        arguments:
            - @=service("csbill.payment.method.options").get('paypal_express_checkout')
            - @payum.buzz.client

    csbill.payment.method.options:
        class: CSBill\PaymentBundle\Manager\PaymentSettingsManager
        arguments: [@doctrine]

    csbill.payment.twig_extension:
        class: %csbill.payment.twig_extension.class%
        arguments: [@csbill_payment.method.manager]
        tags:
            - { name: twig.extension }
