services:
    fos_user.user_manager.default:
        class: SolidInvoice\UserBundle\Manager\UserManager
        public: false
        lazy: true
        arguments: ['@fos_user.util.password_updater', '@fos_user.util.canonical_fields_updater', '@fos_user.object_manager', '%fos_user.model.user.class%']

    SolidInvoice\UserBundle\Repository\ApiTokenRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceUserBundle:ApiToken']

    SolidInvoice\UserBundle\Repository\ApiTokenHistoryRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceUserBundle:ApiTokenHistory']

    SolidInvoice\UserBundle\Repository\UserRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceUserBundle:User']
