filter:
    excluded_paths: [vendor/*, web/*, app/*, bin/*]
    paths:
        - 'src/*'

before_commands:
    - composer install

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend: true
    js_hint: true
    php_cs_fixer: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR2
    sensiolabs_security_checker: true
    php_loc: true
    php_hhvm: false
    external_code_coverage:
        config:
            timeout: 300