filter:
    excluded_paths: [vendor/*, web/*, app/*, bin/*]
    paths:
        - 'src/*'

before_commands:
    - composer install

tools:
    php_mess_detector:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
        config:
            naming_rules: { boolean_method_name: true }
            controversial_rules: { camel_case_class_name: true, camel_case_property_name: true, camel_case_method_name: true, camel_case_parameter_name: true, camel_case_variable_name: true }
    php_cpd:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
    php_pdepend: true
    js_hint:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
    php_cs_fixer:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
        config:
            level: all
    php_analyzer: true
    php_code_sniffer:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
        config:
            standard: PSR2
    sensiolabs_security_checker:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
    php_loc:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]
    external_code_coverage:
        filter:
            excluded_paths: [vendor/*, web/*, app/*, bin/*]