language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

env:
  global:
    - SYMFONY_ENV=test
    - secure: cJUez1SjrfZlW0GkXpMcXBakzGrAqxDCo4Bb+KfFcI+K6NaWLD5f3AXBWu3LU7BpzKjLDbFc9HCQXETlkfH5S5/bDURuoWN6iW5IO52/8xM44Ld36cF0E9Hl+xSTZ3cGKFTqzJ3fwGVrikXgHFIIslNwjasCnhQz3zlxinaBRSY=
    - secure: OMe6ZQMB2CEYJoJh9adQhmJVnRB0MmSdBwbLg/dboZLItvO0CVxMvNwJrOqbqMHopyldw/A+8MhpGzVJv3QrEZaznnA90yPO5+f5BabgX3Xu47tYc5yG4q/Uda4hjNrA7nK36O+cnaXLqyVZKsfJx8dXEA2ybHmF65kSW65HubM=

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install --prefer-source -n
  - php app/console assets:install -n
  - php app/console assetic:dump -n

before_script:
  - mysql -e 'create database csbill;'
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm"* ]]; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - php app/check.php
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - bash travis/travis-ci-apache.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - bash travis/sauce.sh

script:
  - php app/console security:check
  - bash travis/behat.sh
  - bash travis/phpunit.sh

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6"* ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6"* ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;
  - php ./bin/coveralls -v

notifications:
  webhooks:
    - http://savage.csbill.org/savage/travis
  hipchat:
    rooms:
      secure: Wc5cg/o//7DW9G0mosA5wmmECr9+R7S/FmVFvZU2mBBpfaE5nY873hePRrMK/Dhiu2aD5R/ll6d7b3mT7oiWzO/rMgQ+U/DcMmgqHYiYrtEz4umi+1EuSLURDAxyv3rDiXHhEWwbYcHfE1Tcfs07Aj4JWSZheploBRpg3iqzMbw=
