parameters:
    csbill_quote.menu.class: CSBill\QuoteBundle\Menu\Main

services:
    csbill_quote.menu:
        class: %csbill_quote.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: quotes_index,  method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_view,   method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_create, method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_edit, method: quotesMenu }

    quote.total.listener:
        class: CSBill\QuoteBundle\Listener\Doctrine\QuoteTotalListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    quote.form.type:
        class: CSBill\QuoteBundle\Form\Type\QuoteType
        arguments: [@=service('doctrine').getManager().getRepository('CSBillCoreBundle:Tax')]
        tags:
            - { name: form.type, alias: quote }

    quote.item.form.type:
        class: CSBill\QuoteBundle\Form\Type\ItemType
        arguments: [@=service('doctrine').getManager().getRepository('CSBillCoreBundle:Tax')]
        tags:
            - { name: form.type, alias: quote_item }