parameters:
    csbill_quote.menu.class: CSBill\QuoteBundle\Menu\Main

services:
    csbill_quote.menu:
        class: %csbill_quote.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: quotes_index,  method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_view,   method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_create, method: quotesMenu }
            - { name: cs_core.menu, menu: quotes_create, method: quotesMenu }
