services:
    _defaults:
        autowire: true
        tags:
            - { name: form.type }

    SolidInvoice\CoreBundle\Form\Type\ImageUploadType:
        arguments:
            $secret: '%secret%'

    SolidInvoice\CoreBundle\Form\Type\DiscountType: ~
