services:
    _defaults:
        tags: ['form.handler']

    _instanceof:
        SolidWorx\FormHandler\FormHandlerInterface:
            autowire: true
            public: false

    SolidInvoice\InvoiceBundle\Form\Handler\:
        resource: '../../../Form/Handler'
        lazy: true
        arguments:
            $stateMachine: '@state_machine.invoice'