services:
    client.notification.listener:
        class: SolidInvoice\ClientBundle\Listener\ClientListener
        calls:
            - ['setContainer', ['@service_container']]
        tags:
            - { name: 'doctrine.event_listener', event: postPersist }
            - { name: 'doctrine.event_listener', event: postUpdate }
            - { name: 'doctrine.event_listener', event: prePersist }