services:
    solidinvoice_client.menu:
        class: SolidInvoice\ClientBundle\Menu\Builder
        tags:
            - { name: 'cs_core.menu', menu: top, method: topMenu }
            - { name: 'cs_core.menu', menu: clients_index, method: clientsMenu }
            - { name: 'cs_core.menu', menu: clients_view, method: clientViewMenu }
            - { name: 'cs_core.menu', menu: clients_add, method: clientsMenu }
            - { name: 'cs_core.menu', menu: clients_edit, method: clientsMenu }

    SolidInvoice\ClientBundle\Repository\ClientRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceClientBundle:Client']

    SolidInvoice\ClientBundle\Repository\CreditRepository:
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceClientBundle:Credit']

    solidinvoice_client.contact_type.repository:
        class: SolidInvoice\ClientBundle\Repository\ContactTypeRepository
        factory: ['@doctrine', getRepository]
        arguments: ['SolidInvoiceClientBundle:ContactType']

    solidinvoice_client.contact_type.values:
        class: SolidInvoice\ClientBundle\Repository\ContactTypeRepository
        factory: ['@solidinvoice_client.contact_type.repository', findAll]
