datagrid:
    active_client_grid:
	title: Active Clients
	icon: fa-check
	source:
	    repository: CSBillClientBundle:Client
	    method: getGridQuery
	columns:
	    id:
		name: id
		label: ID
		editable: false
		cell: integer
	    name:
		name: name
		label: Name
		editable: false
		cell: string
	    website:
		name: website
		label: Website
		editable: false
		cell: uri
	    status:
		name: status
		label: Status
		editable: false
		cell: client_status
	    created:
		name: created
		label: Created
		editable: false
		cell: date
	search:
	    fields:
		- name
		- website
		- status
	actions:
	    archive:
		label: Archive
		icon: archive
		confirm: "Are you sure you want to archive the selected rows?"
		action: _clients_archive
		className: warning
	    delete:
		label: Delete
		icon: ban
		confirm: "Are you sure you want to delete the selected rows?"
		action: _clients_delete
		className: danger
	filters:
	    name:
		type: string
	    website:
		type: string
	    status:
		type: select
		multiple: true
		source:
		    repository: CSBillClientBundle:Client
		    method: getStatusList
	    created:
		type: date