_clients_index:
    path:   /
    defaults:  { _controller: CSBillClientBundle:Default:index }
    options:
        expose: true

_clients_add:
    path:   /add
    defaults:  { _controller: CSBillClientBundle:Default:add }

_clients_edit:
    path:   /edit/{id}
    defaults:  { _controller: CSBillClientBundle:Default:edit }

_clients_view:
    path:   /view/{id}
    defaults:  { _controller: CSBillClientBundle:Default:view }

_clients_delete:
    path:   /ajax/delete/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:deleteclient }
    methods: [POST]

_clients_info:
    path:   /ajax/info/{id}/{type}
    defaults:
        _controller: CSBillClientBundle:Ajax:info
        type: quote
    options:
        expose: true

_clients_add_credit:
    path:   /ajax/credit/add/{id}
    defaults:  { _controller: CSBillClientBundle:Credit:add }
    options:
        expose: true

_clients_add_contact:
    path:   /ajax/contacts/add/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:addcontact }

_clients_edit_contact:
    path:   /ajax/contacts/edit/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:editcontact }

_clients_contact_card:
    path:   /ajax/contacts/card/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:contactcard }
    options:
        expose: true

_clients_delete_contact:
    path:   /ajax/contacts/delete/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:deletecontact }
    methods: [POST]
    options:
        expose: true
