parameters:
    csbill_client.menu.class: CSBill\ClientBundle\Menu\ClientMenu
    validator.contact_details.primary.class: CSBill\ClientBundle\Validator\Constraints\ContactDetailPrimaryValidator

services:
    csbill_client.menu:
        class: %csbill_client.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: clients_index, method: clientsMenu }
            - { name: cs_core.menu, menu: clients_view, method: clientsMenu }
            - { name: cs_core.menu, menu: clients_add, method: clientsMenu }

    validator.contact_details.primary:
        class: %validator.contact_details.primary.class%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: validator.constraint_validator, alias: contact_detail_primary }
