parameters:
    csbill_client.menu.class: CSBill\ClientBundle\Menu\ClientMenu
    csbill_client.contact_type.repository.class: CSBill\ClientBundle\Repository\ContactTypeRepository
    csbill_client.contact_types.twig.extension.class: CSBill\ClientBundle\Twig\Extension\ContactTypesExtension
    csbill_client.contact.form.type.class: CSBill\ClientBundle\Form\Contact

services:
    csbill_client.menu:
        class: %csbill_client.menu.class%
        tags:
            - { name: cs_core.menu, menu: top, method: topMenu }
            - { name: cs_core.menu, menu: clients_index, method: clientsMenu }
            - { name: cs_core.menu, menu: clients_view, method: clientViewMenu }
            - { name: cs_core.menu, menu: clients_add, method: clientsMenu }

    csbill_client.contact.form.type:
        class: %csbill_client.contact.form.type.class%
        arguments: [@csbill_client.contact_type.values]
        tags:
            - { name: form.type, alias: contact }

    csbill_client.contact_types.twig.extension:
        class: %csbill_client.contact_types.twig.extension.class%
        arguments: [@doctrine]
        tags:
            - { name: twig.extension }

    csbill_client.contact_type.repository:
        class: %csbill_client.contact_type.repository.class%
        factory_service: doctrine
        factory_method:  getRepository
        arguments:
            - "CSBillClientBundle:ContactType"

    csbill_client.contact_type.values:
        class: %csbill_client.contact_type.repository.class%
        factory_service: csbill_client.contact_type.repository
        factory_method:  findAll

    csbill.client.grid:
        class: CSBill\ClientBundle\Grid\ClientGrid
        arguments: [@doctrine, @session]