cs_bill_settings:
    system:
        children:
            general:
                settings:
                    - { name: 'app_name', value : 'CSBill'}
                    - { name: 'logo', value: "", type : 'image_upload'}
    quote:
        settings:
            - { name: email_subject, value: "New Quotation - #{id}", description: "To include the id of the quote in the subject, add the placeholder {id} where you want the id"}
    invoice:
        settings:
            - { name: email_subject, value: "New Invoice - #{id}", description: "To include the id of the invoice in the subject, add the placeholder {id} where you want the id"}
    email:
        settings:
            - { name: from_name, value: ""}
            - { name: from_address, value: ""}
            - { name: format, value: "both", type: "radio", options: {"html" : "html", "text" : "text", "both" : "both"}, description: "In what format should emails be sent."}

    hipchat:
        settings:
            - { name: auth_token, value: ~ }
            - { name: server_url, value: "https://api.hipchat.com" }
            - { name: notify, type: checkbox }
            - { name: message_color, type: select2, value: yellow, options: {yellow : yellow, red : red, gray : gray, green : green, purple : purple, random : random} }
            - { name: message_format, type: select2, value: text, options: {html: html, text: text} }