parameters:
    database_driver: pdo_mysql
    database_host: %database.host%
    database_port: 3306
    database_name: %database.name%
    database_user: %database.name%
    database_password: %database.name%

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: en_US
    currency: ZAR
    secret: f3eeaeacfbc4c54c9e49737958edef5c
