payum:
    security:
        token_storage:
            CSBill\PaymentBundle\Entity\SecurityToken: {doctrine: orm}
    storages:
        CSBill\PaymentBundle\Entity\Payment:  {doctrine: orm}
    contexts:
        credit:
            offline: ~
        cash:
            offline: ~

        bank_transfer:
            offline: ~

        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username:  NOT USED
                password:  NOT USED
                signature: NOT USED
                sandbox: true
                apis:
                    - csbill.payment.payum.paypal_express_checkout_api
                extensions:
                    - csbill.payment.payum.extension.update_payment_details_extension