cs_bill_core:
    resource: "@CSBillCoreBundle/Resources/config/routing.yml"
    prefix:   /

cs_bill_install:
    resource: "@CSBillInstallBundle/Controller/"
    type:     annotation
    prefix:   /install

cs_user:
    resource: "@CSUserBundle/Resources/config/routing.yml"

cs_client_bundle:
    resource: "@CSClientBundle/Resources/config/routing.yml"
