cs_settings:
    resource: "@CSSettingsBundle/Resources/config/routing.yml"
    prefix:   /

csbill_core:
    resource: "@CSBillCoreBundle/Resources/config/routing.yml"
    prefix:   /

csbill_install:
    resource: "@CSBillInstallBundle/Resources/config/routing.yml"
    prefix:   /install

cs_user:
    resource: "@CSUserBundle/Resources/config/routing.yml"

csbill_client:
    prefix:   /clients
    resource: "@CSBillClientBundle/Resources/config/routing.yml"

csbill_quote:
    prefix: /quotes
    resource: "@CSBillQuoteBundle/Resources/config/routing.yml"

csbill_invoice:
    prefix: /invoices
    resource: "@CSBillInvoiceBundle/Resources/config/routing.yml"

csbill_item:
    resource: "@CSBillItemBundle/Resources/config/routing.yml"
    prefix:   /items

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"