cs_bill_core:
    resource: "@CSBillCoreBundle/Resources/config/routing.yml"
    prefix:   /

csbill_install:
    resource: "@CSUserBundle/Resources/config/routing.yml"
    prefix:   /install

cs_user:
    resource: "@CSUserBundle/Resources/config/routing.yml"

cs_client_bundle:
    resource: "@CSClientBundle/Resources/config/routing.yml"

csbill_quote_bundle:
    resource: "@CSBillQuoteBundle/Resources/config/routing.yml"