cs_bill_core:
    resource: "@CSBillCoreBundle/Resources/config/routing.yml"
    prefix:   /

cs_bill_install:
    resource: "@CSBillInstallBundle/Controller/"
    type:     annotation
    prefix:   /install

cs_bill_user:
    resource: "@CSBillUserBundle/Resources/config/routing.yml"
    #resource: "@CSBillUserBundle/Controller/"
    #type:     annotation

cs_client_bundle:
    resource: "@CSClientBundle/Resources/config/routing.yml"
