jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost:      10

    role_hierarchy:
        ROLE_ADMIN:       ~
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CLIENT:      ROLE_USER
        ROLE_USER: ~

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        installer:
            pattern:  ^/install(.*)
            anonymous: ~

        external:
            pattern:  ^/view/(quote|invoice)/([a-zA-Z0-9-]{36})
            anonymous: true
            context: frontend

        login:
            pattern:  ^/login$
            anonymous: ~

        password_reset:
            pattern:  ^/resetting(.*)
            anonymous: ~

        main:
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern:    ^/
            context: frontend
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/view/(quote|invoice)/([a-zA-Z0-9-]), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/install(.*), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }