_dashboard:
    pattern:  /dashboard
    defaults: { _controller: CSBillCoreBundle:Dashboard:index }

_home:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: _dashboard
        permanent: true

_image_upload:
    pattern:  /upload
    defaults: { _controller: CSBillCoreBundle:Upload:imageUpload }
