_dashboard:
    pattern:  /dashboard
    defaults: { _controller: CSBillCoreBundle:Dashboard:index }

_home:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: _dashboard
        permanent: true

_image_upload:
    pattern:  /upload
    defaults: { _controller: CSBillCoreBundle:Upload:imageUpload }

_view_quote_external:
    pattern:  /view/quote/{uuid}
    defaults:
        _controller: CSBillCoreBundle:View:viewquote
    requirements:
        uuid: "[a-zA-Z0-9-]{36}"

_view_invoice_external:
    pattern:  /view/invoice/{uuid}
    defaults:
        _controller: CSBillCoreBundle:View:viewinvoice
    requirements:
        uuid: "[a-zA-Z0-9-]{36}"

_tax_rates:
    pattern: /tax/rates
    defaults: { _controller: CSBillCoreBundle:Tax:rates }

_add_tax_rate:
    pattern: /tax/rates/add
    defaults: { _controller: CSBillCoreBundle:Tax:add }

_edit_tax_rate:
    pattern: /tax/rates/edit/{id}
    defaults: { _controller: CSBillCoreBundle:Tax:add }

_delete_tax_rate:
    pattern: /tax/rates/delete/{id}
    defaults: { _controller: CSBillCoreBundle:Tax:delete }

_get_tax_rate:
    pattern: /tax/rates/get/{id}
    defaults: { _controller: CSBillCoreBundle:Tax:get }
    options:
        expose: true