parameters:
    cs_bill_core.menu.renderer.class: CSBill\CoreBundle\Menu\Renderer
    cs_bill_core.menu.provider.class: CSBill\CoreBundle\Menu\Provider
    cs_bill_core.twig.menu.class: CSBill\CoreBundle\Twig\Extension\MenuExtension
    cs_bill_core.menu_storage.class: CSBill\CoreBundle\Menu\Storage\MenuStorage

services:
    cs_bill_core.menu.renderer:
        class: %cs_bill_core.menu.renderer.class%
        arguments: [@service_container, @knp_menu.factory]

    cs_bill_core.menu.provider:
        class: %cs_bill_core.menu.provider.class%
        arguments: [@cs_bill_core.menu.storage]

    cs_bill_core.menu.storage:
        class: %cs_bill_core.menu_storage.class%

    cs_bill_core.twig.menu:
        class: %cs_bill_core.twig.menu.class%
        calls:
            - [ setRenderer, [ @cs_bill_core.menu.renderer ] ]
            - [ setProvider, [ @cs_bill_core.menu.provider ] ]
        tags:
            - { name: twig.extension }
