imports:
    - { resource: twig.yml }

parameters:
    csbill_core.menu.renderer.class: CSBill\CoreBundle\Menu\Renderer
    csbill_core.menu.provider.class: CSBill\CoreBundle\Menu\Provider
    csbill_core.menu_storage.class: CSBill\CoreBundle\Menu\Storage\MenuStorage
    csbill_core.menu.factory.class: CSBill\CoreBundle\Menu\Factory
    csbill_core.currrency.class: CSBill\CoreBundle\Util\Currency
    csbill_core.doctrine.type.money.class: CSBill\CoreBundle\Doctrine\Type\Money
    csbill_core.settings.class: CSBill\CoreBundle\Manager\SettingsManager

services:
    csbill_core.menu.factory:
        class: %csbill_core.menu.factory.class%
        arguments: [@router]
    csbill_core.menu.renderer:
        class: %csbill_core.menu.renderer.class%
        arguments: [@service_container, @csbill_core.menu.factory]

    csbill_core.menu.provider:
        class: %csbill_core.menu.provider.class%
        arguments: [@csbill_core.menu.storage]

    csbill_core.menu.storage:
        class: %csbill_core.menu_storage.class%

    csbill_core.currency:
        class: %csbill_core.currrency.class%
        arguments: [%locale%, %currency%]

    currency:
        alias: csbill_core.currency

    settings:
        class: %csbill_core.settings.class%
        arguments: [@doctrine]
