services:
    _defaults:
        public: false
        tags:
            - { name: twig.extension }

    SolidInvoice\DataGridBundle\Twig\Extension\GridExtension:
        arguments: ['@grid.repository', '@serializer']