services:
    SolidInvoice\PaymentBundle\Action\:
        resource: '../../../Action'
        autowire: true

    SolidInvoice\PaymentBundle\Action\Prepare:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.invoice'