_api_keys_index:
    path: /api
    defaults: { _controller: 'SolidInvoice\UserBundle\Action\ApiIndex' }
    options:
        expose: true

_api_keys_xhr:
    resource: '@SolidInvoiceUserBundle/Resources/config/routing/ajax.yml'
    prefix: /api/xhr
    options:
        expose: true