parameters:
    csbill.installer.check.class : CSBill\InstallBundle\Listener\RequestListener
    csbill.installer.class: CSBill\InstallBundle\Installer\Installer
    csbill.twig.install_extension.class: CSBill\InstallBundle\Twig\InstallExtension

services:
    csbill.installer.check:
        class: %csbill.installer.check.class%
        arguments: [@csbill.installer, @router]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }

    csbill.installer:
        class: %csbill.installer.class%
        calls:
            - [ setContainer, [ @service_container ] ]

    csbill.twig.install_extension:
        class: %csbill.twig.install_extension.class%
        arguments: [ @csbill.installer ]
        tags:
            - { name: twig.extension }

    csbill.installer.database.migration:
        class: CSBill\InstallBundle\Installer\Database\Migration
        arguments: [@filesystem]
        calls:
            - [setContainer, [@service_container]]