parameters:
    csbill.installer.class: CSBill\InstallBundle\Installer\Installer
    csbill.twig.install_extension.class: CSBill\InstallBundle\Twig\InstallExtension

services:
    installation.scenario.flow:
        class: CSBill\InstallBundle\Process\InstallScenario
        calls:
            - [setContainer, [@service_container]]
        tags:
             - { name: sylius.process.scenario, alias: install }

    csbill.installer.check:
        class: CSBill\InstallBundle\Listener\RequestListener
        arguments: [%installed%, @router, %kernel.debug%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }






    csbill.installer:
        class: %csbill.installer.class%
        calls:
            - [ setContainer, [ @service_container ] ]

    csbill.twig.install_extension:
        class: %csbill.twig.install_extension.class%
        arguments: [ @csbill.installer ]
        tags:
            - { name: twig.extension }

    csbill.installer.database.migration:
        class: CSBill\InstallBundle\Installer\Database\Migration
        arguments: [@filesystem]
        calls:
            - [setContainer, [@service_container]]

    csbill.installer.database.fixtures:
        class: CSBill\InstallBundle\Installer\Database\FixtureLoader
        calls:
            - [setContainer, [@service_container]]
