services:
    _defaults:
        public: false
        tags:
            - { name: kernel.event_subscriber }

    SolidInvoice\InstallBundle\Listener\RequestListener:
        arguments: ['%installed%', '@router', '%kernel.debug%']

    SolidInvoice\InstallBundle\Listener\UpgradeListener:
        arguments: ['%installed%', '@doctrine', '@solidinvoice.installer.database.migration']