services:
    _defaults:
        autoconfigure: true
        autowire: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $installed: '%env(installed)%'

    SolidInvoice\InstallBundle\Installer\Database\Migration:
        arguments: ['@filesystem']
        public: true
        calls:
            - [setContainer, ['@service_container']]

    SolidInvoice\InstallBundle\Command\InstallCommand: ~
