services:
    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            public: false
            tags: ['kernel.event_subscriber']

    _defaults:
        public: false
        autowire: true

    SolidInvoice\SettingsBundle\Listener\:
        resource: '../../../Listener'

    SolidInvoice\SettingsBundle\Listener\MailerSettingsEnvListener:
        arguments:
            $installed: '%installed%'