services:

    _defaults:
        autowire: true

    SolidInvoice\SettingsBundle\SystemConfig:
        lazy: true

    SolidInvoice\SettingsBundle\Repository\SettingsRepository:
        factory: ['@doctrine', 'getRepository']
        arguments: ['SolidInvoiceSettingsBundle:Setting']

    settings:
        alias: SolidInvoice\SettingsBundle\SystemConfig
