_invoices_index:
    pattern:   /
    defaults:  { _controller: CSBillInvoiceBundle:Default:index }

_invoices_create:
    pattern:   /create
    defaults:  { _controller: CSBillInvoiceBundle:Default:create }

_invoices_edit:
    pattern:   /edit/{id}
    defaults:  { _controller: CSBillInvoiceBundle:Default:edit }

_invoices_view:
    pattern:   /view/{id}
    defaults:  { _controller: CSBillInvoiceBundle:Default:view }

# Actions routes

_cancel_invoice:
    pattern:   /action/cancel/{id}
    defaults:  { _controller: CSBillInvoiceBundle:Actions:cancel }

_pay_invoice:
    pattern:   /action/pay/{id}
    defaults:  { _controller: CSBillInvoiceBundle:Actions:pay }

_send_invoice:
    pattern:   /action/send/{id}
    defaults:  { _controller: CSBillInvoiceBundle:Actions:send }